version: '3.9'

services:
  backend:
    build:
      context: ./project/backend
      dockerfile: DOCKERFILE
    image: go-backend
    container_name: go-backend
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    env_file: .backend.env
    restart: on-failure
      

  redis:
    image: redis:6.2.4-alpine
    ports:
      - '6379:6379'

  db:
    image: mysql:8.0.25
    ports:
      - '3307:3306'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file: .db.env
    volumes:
      - MYDB:/var/lib/mysql
volumes:
  MYDB:
